#Deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsbc-financial-deployment
  labels:
    app: hsbc-financial
spec:
  replicas: 2  # 实例数为2
  selector:
    matchLabels:
      app: hsbc-financial
  strategy:
    type: RollingUpdate  # 配置更新策略为滚动更新
    rollingUpdate:
      maxUnavailable: 1  # 更新时最大不可用实例数
      maxSurge: 1        # 更新时最大新增实例数
  template:
    metadata:
      labels:
        app: hsbc-financial
    spec:
      affinity:
        podAntiAffinity:  # 配置反亲和性策略
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hsbc-financial
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: hsbc-financial-container
          image: registry.cn-hangzhou.aliyuncs.com/magnus/hsbc-financial:v1.0.5  # 指定镜像
          ports:
            - containerPort: 8080  # 容器暴露端口8080
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 4Gi
              memory: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 2Gi
              memory: 512Mi

---
# Service 配置
apiVersion: v1
kind: Service
metadata:
  name: hsbc-financial-service
spec:
  type: NodePort  # Service类型为NodePort，暴露端口
  selector:
    app: hsbc-financial
  ports:
    - port: 8080          # Service的端口
      targetPort: 8080    # Pod中容器的端口
      nodePort: 30080     # 节点上暴露的端口（30000-32767间未被占用的端口）

---
# 自动扩缩容配置
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hsbc-financial-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hsbc-financial-deployment  # 关联的Deployment名称
  minReplicas: 2    # 最小实例数
  maxReplicas: 10   # 最大实例数，根据需要调整
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # 当CPU利用率超过80%时触发扩容
